#!/bin/bash

[ $# -ge 2 ] || {
    echo "usage: self-test-perfect textfile minimodem_args" 1>&2
    exit 1
}
textfile="$1"
shift
minimodem_args="$*"

TMPF=/tmp/minimodem-test.$$
trap "rm -f $TMPF" 0

# test for "confidence=1.00" and "rate perfect"
./self-test "$textfile" $minimodem_args 2>&1 | tee $TMPF

ndata=$(wc -c <$textfile)

match="ndata=$ndata confidence=1.00 .* (rate perfect)"
grep -q "$match" $TMPF || {
echo "Not perfect; expected: $match"
  exit 1
}
echo "Perfect!"
exit 0
