#!/bin/bash

MINIMODEM="${MINIMODEM-./minimodem}"
[ -f "$MINIMODEM" ] || {
    MINIMODEM="../src/minimodem"
    [ -f "$MINIMODEM" ] || {
	echo "E: cannot find minimodem in ./ or ../src/" 1>&2
	exit 1
    }
}

[ $# -ge 2 ] || {
    echo "usage: self-test textfile minimodem_args" 1>&2
    exit 1
}
textfile="$1"
shift
minimodem_args="$*"

TMPF="/tmp/minimodem-test-$$.wav"
trap "rm -f $TMPF" 0

set -e
echo
echo "$MINIMODEM ... $minimodem_args < $textfile"
$MINIMODEM --tx -T 1 --file $TMPF $minimodem_args < "$textfile"
# ls -l $TMPF
$MINIMODEM --rx --file $TMPF $minimodem_args | diff "$textfile" -

