#!/bin/bash
# 
# run-test
# 
# Copyright (C) 2011 Kamal Mostafa <kamal@whence.com>
# 
# NO LICENSE HAS BEEN SPECIFIED OR GRANTED FOR THIS WORK.
# 
# 


TMPDIR=/tmp/run-test-$$
mkdir "$TMPDIR" || exit
trap "rm -rf $TMPDIR" 0

let nfail=0

for i in ../testdata/*/*.wav
do
    f="${i##*/}"
    rate="${f#*-}"
    rate="${rate%%-*}"

    echo TEST	./minimodem "$i" "$rate" 
    ./minimodem "$i" "$rate" >$TMPDIR/out 2>$TMPDIR/err

    t="${f%%-*}"

    egrep 'CARRIER|TONE' $TMPDIR/err
#    sum -r ../testdata/$t-*.txt $TMPDIR/out
    cmp ../testdata/$t-*.txt $TMPDIR/out
    if [ $? -eq 0 ]
    then
	echo "@@@ PASS $f"
    else
	echo "						@@@ FAIL $f"
	let nfail=nfail+1
    fi

    echo
done

exit $nfail

